export interface ServiceAgent {
  name: string;
  title: string;
  desc: string;
  tools: string[];
  confidence: string;
}

export interface ServiceProcess {
  step: string;
  title: string;
  desc: string;
}

export interface ServiceData {
  slug: string;
  num: string;
  icon: string;
  name: string;
  tagline: string;
  price: string;
  priceNote: string;
  roles: string;
  heroDesc: string;
  color: string;
  accentVar: string;
  accent: string;
  border: string;
  saves: string;
  features: string[];
  detailedFeatures: { title: string; desc: string }[];
  agents: ServiceAgent[];
  process: ServiceProcess[];
  deliverables: string[];
  faq: { q: string; a: string }[];
}

export const services: ServiceData[] = [
  {
    slug: "finance-core",
    num: "01",
    icon: "💰",
    name: "Finance Core",
    tagline: "Your complete finance department — AI-powered, human-reviewed",
    price: "$500/mo",
    priceNote: "Replaces $14,500+/mo in-house cost",
    roles: "Bookkeeper · Accountant · Payroll · Tax",
    heroDesc: "From daily bookkeeping to board-ready financials — our AI-augmented finance team handles your entire accounting function. Every transaction classified, reconciled, and reported with confidence scoring and human oversight.",
    color: "from-teal/20 to-teal/5",
    accentVar: "--color-teal",
    accent: "text-teal",
    border: "border-teal/20",
    saves: "$14,500+/mo",
    features: [
      "Daily transaction posting & reconciliation",
      "P&L, balance sheet & cash flow reports",
      "Full payroll computation & payslips",
      "VAT, WHT & income tax compliance",
      "Board-ready monthly management packs",
    ],
    detailedFeatures: [
      { title: "Automated Bookkeeping", desc: "Every transaction is captured, classified and posted automatically using AI pattern recognition. Bank feeds are reconciled daily with 95%+ accuracy before human review." },
      { title: "Financial Reporting Suite", desc: "Monthly P&L, balance sheet, cash flow statement and trial balance — generated automatically with AI-written commentary explaining variances and trends." },
      { title: "Full-Cycle Payroll", desc: "Salary computation, statutory deductions (tax, pension, NHF), payslip generation and distribution. Variance detection flags anomalies before approval." },
      { title: "Tax Compliance Engine", desc: "Automated VAT/WHT calculations, filing preparation, deadline tracking and remittance scheduling. Never miss a filing deadline again." },
      { title: "Management Packs", desc: "Board-ready monthly reports with executive summaries, KPI dashboards, runway modelling and cash flow forecasts — delivered on schedule every month." },
      { title: "Accounts Payable & Receivable", desc: "Invoice generation, aging reports, payment reminders, vendor management and cash application — all automated with human approval gates." },
    ],
    agents: [
      {
        name: "The Ledger Keeper",
        title: "Bookkeeper Agent",
        desc: "Daily transaction processing, reconciliation, AP/AR management, invoice drafting, petty cash and expense management",
        tools: ["Transaction Posting", "Bank Reconciliation", "Invoice Creation", "Expense Claims", "Receipt Matching", "AR/AP Aging Reports"],
        confidence: "Auto-approves routine postings >90%. Flags unusual amounts or new vendors for review.",
      },
      {
        name: "The Controller",
        title: "Accountant Agent",
        desc: "Month-end close, financial reporting, P&L, balance sheet, variance analysis, accruals/deferrals, management packs",
        tools: ["Report Generation", "Cash Flow Forecasting", "Variance Analysis", "Runway Modelling", "Financial Commentary", "Board Packs"],
        confidence: "Generates draft reports autonomously. All financial statements require Tier 1 review before delivery.",
      },
      {
        name: "The Payroll Officer",
        title: "Payroll Agent",
        desc: "Full payroll cycle: salary computation, statutory deductions, payslips, remittances, variance detection",
        tools: ["Pay Run Calculation", "Payslip Generation", "Payment Batching", "Leave Deductions", "Termination Pay", "Remittance Scheduling"],
        confidence: "Computes payroll autonomously but all pay runs require Tier 2 supervisor approval before disbursement.",
      },
      {
        name: "The Tax Guardian",
        title: "Tax Compliance Agent",
        desc: "Tax calculations (VAT/WHT/income tax), filing preparation, deadline management, remittance scheduling",
        tools: ["Tax Liability Calculation", "VAT Returns", "WHT Schedules", "Filing Deadlines", "Tax Authority Submissions", "Compliance Reports"],
        confidence: "All tax filings require Tier 2 supervisor review. Deadline alerts are fully autonomous.",
      },
    ],
    process: [
      { step: "01", title: "Data Onboarding", desc: "We connect to your bank feeds, accounting software and payment platforms. Historical data is migrated and validated." },
      { step: "02", title: "AI Training", desc: "Our agents learn your chart of accounts, vendor patterns, expense categories and reporting preferences from your historical data." },
      { step: "03", title: "Parallel Running", desc: "Week 1-2: AI processes transactions alongside your existing system. Our team validates every output for accuracy." },
      { step: "04", title: "Full Handover", desc: "Once validated, AI takes over daily operations with human oversight. You receive daily reconciliation confirmations and monthly management packs." },
    ],
    deliverables: [
      "Daily bank reconciliation reports",
      "Monthly P&L, balance sheet & cash flow",
      "Payroll processing & payslips (bi-weekly/monthly)",
      "VAT/WHT returns & tax filing prep",
      "Board-ready management pack",
      "Real-time access to SolyntaFlow dashboard",
      "Dedicated Slack/Teams channel with your finance team",
    ],
    faq: [
      { q: "What accounting standards do you follow?", a: "We follow IFRS for SMEs by default. We can adapt to US GAAP, UK GAAP or local standards as needed." },
      { q: "Can you handle multi-currency?", a: "Yes. SolyntaFlow supports multi-currency transactions with automatic FX rate lookups and gain/loss calculations." },
      { q: "What if I already use QuickBooks/Xero?", a: "We can work alongside your existing tools or fully migrate you to SolyntaFlow. Either way, you get the same AI-augmented service." },
      { q: "How do you handle sensitive financial data?", a: "Strict NDAs, encrypted data at rest and in transit, role-based access controls, and full audit trails on every action." },
    ],
  },
  {
    slug: "sales-crm-web",
    num: "02",
    icon: "📈",
    name: "Sales, CRM & Web",
    tagline: "From lead generation to deal close — your digital growth engine",
    price: "$250/mo",
    priceNote: "Replaces $13,450+/mo in-house cost",
    roles: "Sales Ops · CRM · Web Dev · SEO",
    heroDesc: "A complete digital sales infrastructure — professional website, SEO visibility, CRM pipeline management and automated follow-up sequences. AI handles the research and drafting while your dedicated team manages relationships.",
    color: "from-lavender/20 to-lavender/5",
    accentVar: "--color-lavender",
    accent: "text-lavender",
    border: "border-lavender/20",
    saves: "$13,450+/mo",
    features: [
      "Professional website build or redesign",
      "SEO setup & Google My Business",
      "CRM data cleaning & enrichment",
      "Automated lead follow-up sequences",
      "Weekly pipeline & forecast reports",
    ],
    detailedFeatures: [
      { title: "Website Development", desc: "Mobile-responsive, SEO-optimized website built with modern frameworks. Landing pages, blog integration, analytics tracking and conversion optimization included." },
      { title: "Search Engine Optimization", desc: "Technical SEO audit, keyword research, on-page optimization, meta tag management, sitemap setup and Google Search Console monitoring." },
      { title: "CRM Management", desc: "Full CRM setup, data migration, lead scoring, pipeline stage configuration, automated follow-ups and stale lead re-engagement workflows." },
      { title: "Sales Pipeline Analytics", desc: "Weekly pipeline reports, revenue forecasting, conversion rate analysis, deal velocity tracking and team performance dashboards." },
      { title: "Google My Business", desc: "Profile optimization, review management, local SEO, Google Maps visibility and regular update posting for local discoverability." },
      { title: "Outreach Automation", desc: "AI-drafted outreach emails, personalized follow-up sequences, meeting booking automation and lead nurturing campaigns." },
    ],
    agents: [
      {
        name: "The Growth Engine",
        title: "Sales & CRM Agent",
        desc: "Pipeline management, lead enrichment, outreach drafting, forecasting and deal tracking",
        tools: ["Lead Management", "Company Research", "Email Drafting", "Pipeline Reports", "Revenue Forecasting", "Sequence Building"],
        confidence: "Drafts outreach autonomously. All external communications require human approval before sending.",
      },
      {
        name: "The Digital Architect",
        title: "Web & SEO Agent",
        desc: "Website management, keyword research, on-page/technical SEO, Google My Business, local visibility",
        tools: ["Site Analysis", "Keyword Research", "Technical SEO Audit", "GMB Management", "Content Publishing", "Traffic Analytics"],
        confidence: "Technical changes auto-applied for >90% confidence. Content changes require review.",
      },
      {
        name: "The CRM Specialist",
        title: "CRM Data Agent",
        desc: "CRM data cleaning, record enrichment, lead follow-up automation, stale lead re-engagement, pipeline hygiene",
        tools: ["Lead Scoring", "Data Enrichment", "Follow-up Automation", "Stale Lead Detection", "Pipeline Hygiene", "Activity Logging"],
        confidence: "Data cleaning operations auto-approved. Lead status changes flagged for operator review.",
      },
      {
        name: "The Sales Ops Analyst",
        title: "Sales Analytics Agent",
        desc: "Weekly pipeline/forecast reports, monthly sales performance reviews, conversion rate analysis",
        tools: ["Pipeline Analytics", "Revenue Forecasting", "Variance Analysis", "Report Generation", "Chart Building", "Email Distribution"],
        confidence: "Report generation fully autonomous. Forecast adjustments require Tier 1 review.",
      },
    ],
    process: [
      { step: "01", title: "Discovery & Audit", desc: "We audit your current web presence, CRM setup and sales process. Identify quick wins and strategic gaps." },
      { step: "02", title: "Foundation Build", desc: "Website development (or redesign), CRM setup/migration, SEO baseline establishment and Google My Business optimization." },
      { step: "03", title: "Pipeline Activation", desc: "Lead import, scoring rules configured, follow-up sequences activated, outreach templates created and tested." },
      { step: "04", title: "Optimize & Scale", desc: "Weekly pipeline reviews, A/B testing outreach, SEO ranking improvements, conversion rate optimization and growth strategy." },
    ],
    deliverables: [
      "Professional website with analytics",
      "Full CRM setup with pipeline stages",
      "Weekly pipeline & forecast reports",
      "SEO monthly progress reports",
      "Automated follow-up sequences",
      "Google My Business management",
      "Lead enrichment & scoring automation",
    ],
    faq: [
      { q: "What CRM platforms do you support?", a: "We work with HubSpot, Salesforce, Pipedrive, Zoho and our own SolyntaFlow CRM. We can migrate between platforms." },
      { q: "Do you build custom websites?", a: "Yes — from single-page landing sites to full multi-page applications. We use Next.js, React and modern frameworks for performance." },
      { q: "How do you handle lead data privacy?", a: "All lead data stays within your CRM. We follow GDPR/CCPA principles and sign NDAs covering all customer data." },
      { q: "Can you manage our social selling?", a: "Social media is covered by our Marketing module. The Sales module focuses on direct pipeline management and outreach." },
    ],
  },
  {
    slug: "customer-service",
    num: "03",
    icon: "💬",
    name: "AI Customer Service",
    tagline: "24/7 intelligent support across every channel",
    price: "$250/mo",
    priceNote: "Replaces $2,750+/mo in-house cost",
    roles: "WhatsApp · Email · Website Chatbot",
    heroDesc: "AI-powered customer support that never sleeps. Trained on YOUR business data, operating across WhatsApp, email and web chat with intelligent escalation to human agents when needed.",
    color: "from-coral/20 to-coral/5",
    accentVar: "--color-coral",
    accent: "text-coral",
    border: "border-coral/20",
    saves: "$2,750+/mo",
    features: [
      "WhatsApp Business AI chatbot (24/7)",
      "Email auto-triage & priority sorting",
      "Website chatbot with lead capture",
      "Human escalation routing",
      "All bots trained on YOUR data",
    ],
    detailedFeatures: [
      { title: "WhatsApp Business Bot", desc: "24/7 conversational AI on WhatsApp — handles FAQs, order status, booking queries, and payment inquiries. Seamlessly escalates complex cases to human agents." },
      { title: "Email Auto-Triage", desc: "Incoming emails are automatically classified by priority, categorized by topic, and routed to the right team. Standard replies drafted for quick approval." },
      { title: "Website Chatbot", desc: "Embedded chatbot that handles visitor queries, captures leads, books appointments and provides product/service information — all trained on your specific knowledge base." },
      { title: "Knowledge Base Management", desc: "We build and maintain a comprehensive knowledge base from your SOPs, FAQs and product documentation. AI agents reference this for consistent, accurate responses." },
      { title: "Escalation Intelligence", desc: "Smart routing based on query complexity, sentiment analysis and confidence scoring. Urgent or complex cases reach human agents within minutes." },
      { title: "Support Analytics", desc: "Query volume trends, response time tracking, resolution rates, customer satisfaction scoring and knowledge base gap analysis." },
    ],
    agents: [
      {
        name: "The 24/7 Responder",
        title: "Multi-Channel Support Agent",
        desc: "Multi-channel customer service: WhatsApp, email, web chat with 24/7 availability",
        tools: ["Knowledge Base Search", "Appointment Booking", "Message Reply", "Ticket Escalation", "Query Classification", "Tone Adaptation"],
        confidence: "FAQ responses auto-sent at >90%. Complex queries drafted for human review before sending.",
      },
      {
        name: "The Email Triage Agent",
        title: "Email Intelligence Agent",
        desc: "Email auto-triage, priority sorting, standard reply drafting, urgent case flagging, thread summarization",
        tools: ["Email Classification", "Priority Sorting", "Reply Drafting", "Urgent Flagging", "Thread Summarization", "Ticket Management"],
        confidence: "Classification is autonomous. All outgoing replies require operator approval.",
      },
      {
        name: "The Website Chatbot",
        title: "Web Chat Agent",
        desc: "Embedded website chatbot for lead capture, product/service queries, appointment booking",
        tools: ["Knowledge Base Search", "Lead Capture", "Appointment Booking", "Availability Checking", "Escalation Routing", "Tone Adaptation"],
        confidence: "Handles 80%+ of queries autonomously. Transfers to human agent for purchase decisions or complaints.",
      },
    ],
    process: [
      { step: "01", title: "Knowledge Capture", desc: "We extract your FAQs, product info, pricing, policies and procedures to build a comprehensive knowledge base." },
      { step: "02", title: "Bot Training", desc: "AI agents are trained on your specific business context, brand voice and escalation rules. Test conversations validate accuracy." },
      { step: "03", title: "Channel Deployment", desc: "Bots deployed across WhatsApp, email and your website. Escalation rules configured. Human agents briefed on handoff protocols." },
      { step: "04", title: "Continuous Learning", desc: "Ongoing knowledge base updates, conversation analysis, accuracy improvements and quarterly performance reviews." },
    ],
    deliverables: [
      "WhatsApp Business AI chatbot (24/7)",
      "Email auto-triage & reply drafting",
      "Website chatbot with lead capture",
      "Comprehensive knowledge base",
      "Monthly support analytics report",
      "Escalation routing & human handoff",
      "Quarterly bot performance review",
    ],
    faq: [
      { q: "Can the bots handle multiple languages?", a: "Yes — our AI agents support English, French, Spanish and Portuguese out of the box. Additional languages can be added on request." },
      { q: "What if the bot gets it wrong?", a: "Confidence scoring ensures uncertain responses are flagged for human review before sending. Incorrect responses trigger knowledge base updates." },
      { q: "Do you integrate with our existing ticketing system?", a: "We integrate with Zendesk, Freshdesk, Intercom, HubSpot Service Hub and custom systems via API." },
      { q: "How quickly can we be live?", a: "Basic FAQ bot in 3-5 days. Full multi-channel deployment with custom training in 2-3 weeks." },
    ],
  },
  {
    slug: "hr-admin",
    num: "04",
    icon: "👥",
    name: "HR & Admin Ops",
    tagline: "People operations, procurement and IT — fully managed",
    price: "$250/mo",
    priceNote: "Replaces $9,750+/mo in-house cost",
    roles: "HR Admin · Procurement · IT Admin",
    heroDesc: "Complete back-office operations — from employee onboarding to vendor management to IT administration. AI handles the workflows while your dedicated team manages the people and relationships.",
    color: "from-gold/20 to-gold/5",
    accentVar: "--color-gold",
    accent: "text-gold",
    border: "border-gold/20",
    saves: "$9,750+/mo",
    features: [
      "Automated onboarding workflows",
      "Leave & PTO tracking management",
      "Vendor contract & PO management",
      "SaaS license tracking & cost monitoring",
      "Compliance database maintenance",
    ],
    detailedFeatures: [
      { title: "Employee Onboarding", desc: "Automated onboarding workflows: offer letter generation, document collection, system access provisioning, welcome emails and training schedule setup." },
      { title: "Leave & Attendance", desc: "PTO request management, leave balance tracking, absence pattern detection and integration with payroll for automatic deductions." },
      { title: "Procurement Management", desc: "Vendor database, PO generation and tracking, contract renewal alerts, invoice matching and approval workflows." },
      { title: "IT Administration", desc: "SaaS license inventory, user provisioning/de-provisioning, subscription cost optimization, security compliance checks and access audits." },
      { title: "Performance Management", desc: "Review cycle scheduling, goal tracking, 360-feedback coordination and performance report compilation." },
      { title: "Compliance & Records", desc: "Employee records management, compliance database maintenance, policy acknowledgment tracking and regulatory document filing." },
    ],
    agents: [
      {
        name: "The HR Administrator",
        title: "HR Operations Agent",
        desc: "Onboarding workflows, employee records, leave/PTO tracking, performance review scheduling, compliance",
        tools: ["Employee Records", "Leave Management", "Deadline Tracking", "Recurring Schedules", "Alert Notifications", "Review Flagging"],
        confidence: "Routine HR admin (leave approvals, record updates) auto-processed. Terminations and policy changes require supervisor.",
      },
      {
        name: "The Procurement Officer",
        title: "Procurement Agent",
        desc: "Vendor contract management, PO generation/tracking, supplier correspondence, invoice approval workflows",
        tools: ["Invoice Processing", "AP Aging Reports", "Document OCR", "Payment Reminders", "Supervisor Reviews", "Budget Checking"],
        confidence: "POs under $5,000 auto-generated. All vendor contracts and large POs require Tier 2 approval.",
      },
      {
        name: "The IT Admin",
        title: "IT Operations Agent",
        desc: "SaaS license tracking, user provisioning/de-provisioning, subscription cost optimization, security compliance",
        tools: ["Alert Management", "Reminder Distribution", "Review Flagging", "Cost Reports"],
        confidence: "License tracking and alerting fully autonomous. Access changes require human authorization.",
      },
    ],
    process: [
      { step: "01", title: "Systems Audit", desc: "We map your current HR processes, vendor relationships, IT stack and compliance requirements." },
      { step: "02", title: "Process Design", desc: "Workflows configured in SolyntaFlow: onboarding checklists, approval chains, PO templates, license inventories." },
      { step: "03", title: "Data Migration", desc: "Employee records, vendor contracts, IT asset inventories imported and validated." },
      { step: "04", title: "Managed Operations", desc: "Your dedicated HR/Admin team runs day-to-day operations with AI automation handling routine tasks." },
    ],
    deliverables: [
      "Automated employee onboarding workflows",
      "Leave/PTO tracking & reporting",
      "Vendor & contract management",
      "PO generation & invoice matching",
      "SaaS license inventory & optimization",
      "Monthly HR & admin operations report",
      "Compliance database maintenance",
    ],
    faq: [
      { q: "Can you handle our specific HR compliance requirements?", a: "Yes. We customize compliance workflows for your jurisdiction — US, UK, Nigeria, or any other market." },
      { q: "Do you replace our HR software?", a: "We can work alongside BambooHR, Gusto, Rippling etc., or provide full HR functionality within SolyntaFlow." },
      { q: "How do you handle confidential employee data?", a: "Role-based access controls, encrypted storage, NDAs and audit trails on every data access." },
      { q: "Can you manage recruitment too?", a: "Basic recruitment support (job posting, resume screening) is included. Full RPO services are available as an add-on." },
    ],
  },
  {
    slug: "marketing",
    num: "05",
    icon: "📣",
    name: "Marketing Department",
    tagline: "A full marketing team — strategy to execution to analytics",
    price: "from $500/mo",
    priceNote: "Replaces $15,000+/mo in-house cost",
    roles: "Social · PPC · Content · SEO · Video · Automation · Analytics",
    heroDesc: "Eight specialized AI agents covering every aspect of modern digital marketing — from content creation and social media to paid ads, SEO, video production, marketing automation and performance analytics. All working together under a unified strategy.",
    color: "from-pink-500/20 to-pink-500/5",
    accentVar: "--color-coral",
    accent: "text-pink-400",
    border: "border-pink-500/20",
    saves: "$15,000+/mo",
    features: [
      "Social media management (3+ platforms)",
      "Google, Meta & LinkedIn ad campaigns",
      "Content marketing & lead magnets",
      "Marketing automation & email sequences",
      "ROI reporting & attribution tracking",
    ],
    detailedFeatures: [
      { title: "Social Media Management", desc: "Content calendar management across 3+ platforms. AI-generated posts with brand voice, scheduling, community engagement, trend monitoring and Canva design briefs." },
      { title: "Paid Advertising", desc: "Google Ads, Meta (Facebook/Instagram), LinkedIn campaign management. Bid optimization, audience targeting, retargeting pixels, lookalike audiences and budget allocation." },
      { title: "Content Marketing", desc: "Blog articles, lead magnets, email newsletters, case studies and whitepapers. AI-drafted, human-edited, SEO-optimized content that drives organic traffic." },
      { title: "SEO Content Programme", desc: "Keyword-optimized content strategy, content gap analysis, backlink strategy, technical SEO monitoring and monthly ranking reports." },
      { title: "Video Production", desc: "Short-form video scripting for Reels, TikTok and YouTube Shorts. Creative briefs, storyboards, editing notes and platform-specific formatting." },
      { title: "Marketing Automation", desc: "Email drip sequences, retargeting campaigns, lead scoring, conversion optimization and workflow automation across your marketing stack." },
      { title: "Performance Analytics", desc: "Campaign ROI reporting, multi-touch attribution, A/B test analysis, competitor intelligence, conversion rate optimization and monthly strategy reviews." },
    ],
    agents: [
      {
        name: "The Social Media Manager",
        title: "Social Media Agent",
        desc: "Content calendar management (3+ platforms), posting/scheduling, community engagement, trend monitoring, Canva design briefs",
        tools: ["Content Publishing", "Post Scheduling", "Design Briefs", "Analytics Tracking", "Campaign Calendar", "Platform Posting"],
        confidence: "Content drafting autonomous. All external posts require operator approval before publishing.",
      },
      {
        name: "The PPC Specialist",
        title: "Paid Ads Agent",
        desc: "Google/Facebook/Instagram/LinkedIn ads management, bid optimization, budget allocation, retargeting",
        tools: ["Traffic Analytics", "Chart Generation", "Performance Reports", "Variance Analysis", "Alert Management", "Review Flagging"],
        confidence: "Bid adjustments within 20% auto-applied. Budget changes and new campaigns require approval.",
      },
      {
        name: "The Content Marketer",
        title: "Content Strategy Agent",
        desc: "Blog articles, lead magnets, email newsletters, content strategy, editorial calendar",
        tools: ["SEO Content Writing", "Blog Generation", "Campaign Calendars", "Content Scheduling", "Keyword Research", "Traffic Analytics"],
        confidence: "Drafts content autonomously. All published content requires editorial review.",
      },
      {
        name: "The SEO Content Strategist",
        title: "SEO Programme Agent",
        desc: "SEO content programme, keyword-optimized articles, content gap analysis, backlink strategy, technical SEO monitoring",
        tools: ["Keyword Research", "Site Analysis", "Ranking Tracking", "Technical Audit", "Content Publishing", "Competitor Analysis"],
        confidence: "Technical SEO fixes auto-applied. Content and link strategy require Tier 1 review.",
      },
      {
        name: "The Video Producer",
        title: "Video Content Agent",
        desc: "Short-form video scripting (Reels/TikTok/Shorts), creative briefs, storyboards, platform formatting",
        tools: ["Script Writing", "Page Drafting", "Competitor Research", "Traffic Analytics"],
        confidence: "Script drafting autonomous. All production briefs require creative director approval.",
      },
      {
        name: "The Marketing Automator",
        title: "Automation Agent",
        desc: "Email drip sequences, retargeting campaigns, lead scoring, workflow automation, conversion optimization",
        tools: ["Sequence Building", "Lead Scoring", "Email Outreach", "Lead Management", "Traffic Analytics", "Alert Notifications"],
        confidence: "Automated sequences run autonomously once approved. New sequence creation requires review.",
      },
      {
        name: "The Marketing Analyst",
        title: "Analytics Agent",
        desc: "Campaign ROI reporting, attribution tracking, A/B test analysis, competitor intelligence",
        tools: ["Traffic Analytics", "Variance Analysis", "Chart Generation", "Report Packs", "Board Packs", "Competitor Research"],
        confidence: "All analytics and reporting fully autonomous. Strategy recommendations flagged for review.",
      },
    ],
    process: [
      { step: "01", title: "Marketing Audit", desc: "Full audit of your current marketing: channels, content, ads, SEO, analytics, competitors and brand positioning." },
      { step: "02", title: "Strategy & Setup", desc: "Marketing strategy document, channel priorities, content calendar, ad account setup, tracking pixels and analytics configuration." },
      { step: "03", title: "Content & Launch", desc: "Initial content batch created, social profiles optimized, ad campaigns launched, email sequences activated." },
      { step: "04", title: "Optimize & Report", desc: "Weekly performance reviews, monthly strategy sessions, continuous A/B testing, budget reallocation and ROI reporting." },
    ],
    deliverables: [
      "Monthly content calendar (3+ platforms)",
      "Weekly social media posting & engagement",
      "Google/Meta/LinkedIn ad management",
      "Monthly blog articles & SEO content",
      "Email marketing sequences",
      "Video scripts & creative briefs",
      "Monthly marketing performance report",
      "Quarterly strategy review",
    ],
    faq: [
      { q: "What platforms do you manage?", a: "Facebook, Instagram, LinkedIn, Twitter/X, TikTok, YouTube, Google Ads, Meta Ads and LinkedIn Ads." },
      { q: "Do you create the actual graphics and videos?", a: "We create design briefs, scripts and storyboards. Canva designs are created in-house. For premium video production, we partner with specialists." },
      { q: "What's the difference between $500 and $1,200/mo tiers?", a: "Entry ($500): 2 platforms, basic content. Growth ($800): 3+ platforms, ads, email. Pro ($1,200): full-service including video, automation and advanced analytics." },
      { q: "How do you measure ROI?", a: "Multi-touch attribution tracking, conversion pixel data, UTM parameters and direct revenue attribution where possible." },
    ],
  },
  {
    slug: "embedded-developers",
    num: "06",
    icon: "💻",
    name: "Embedded Developers",
    tagline: "Senior developers in your team — at a fraction of the cost",
    price: "from $500/mo",
    priceNote: "Replaces $9,350+/mo in-house cost",
    roles: "Full Stack · QA · DevOps · Tech Lead · UI/UX",
    heroDesc: "A complete development team that embeds in yours — full stack developers, QA engineers, DevOps, tech leads and UI/UX designers. All augmented by AI for 3x faster development velocity.",
    color: "from-cyan-400/20 to-cyan-400/5",
    accentVar: "--color-teal",
    accent: "text-cyan-400",
    border: "border-cyan-400/20",
    saves: "$9,350+/mo",
    features: [
      "Dedicated developer in your team & tools",
      "Attends your standups & sprint planning",
      "Frontend, backend & database work",
      "CI/CD pipelines & cloud infrastructure",
      "AI-augmented for 3x faster output",
    ],
    detailedFeatures: [
      { title: "Full Stack Development", desc: "React, Next.js, Vue, Angular frontends. Python, Node.js, Django, Express backends. PostgreSQL, MongoDB, Redis databases. REST and GraphQL APIs." },
      { title: "Mobile Development", desc: "React Native and Flutter for cross-platform mobile apps. Native iOS (Swift) and Android (Kotlin) when performance demands it." },
      { title: "Cloud & DevOps", desc: "AWS, GCP, Azure infrastructure. Docker, Kubernetes containerization. CI/CD with GitHub Actions, GitLab CI. Infrastructure as Code with Terraform." },
      { title: "AI-Augmented Velocity", desc: "Developers use Claude, Cursor and AI coding assistants for 3x faster development. Code review, testing and documentation all AI-accelerated." },
      { title: "Team Integration", desc: "Developers join your Slack/Teams, attend standups, participate in sprint planning and retrospectives. They ARE part of your team." },
      { title: "Quality Assurance", desc: "Automated testing (unit, integration, e2e), code review, performance optimization and security best practices baked into every sprint." },
    ],
    agents: [
      {
        name: "The Full Stack Developer",
        title: "Full Stack Agent",
        desc: "Embedded developer for frontend/backend/database work, AI-assisted coding, sprint delivery and code quality",
        tools: ["Code Generation", "Code Review", "Test Writing", "API Development", "Database Queries", "Documentation"],
        confidence: "Development tasks executed autonomously. All production deployments require team lead approval.",
      },
      {
        name: "The QA Engineer",
        title: "Quality Assurance Agent",
        desc: "Automated test generation, manual test plans, bug tracking, regression testing, CI/CD quality gates",
        tools: ["Test Generation", "Bug Tracking", "Regression Testing", "Quality Gates", "Test Reports", "Coverage Analysis"],
        confidence: "Test generation autonomous. Release sign-offs require Tier 1 review.",
      },
      {
        name: "The DevOps Engineer",
        title: "DevOps Agent",
        desc: "CI/CD pipelines, infrastructure management, Docker/Kubernetes, monitoring, deployment automation",
        tools: ["Pipeline Management", "Container Orchestration", "Monitoring Setup", "Deployment Automation", "Infrastructure as Code", "Incident Response"],
        confidence: "Monitoring and alerting fully autonomous. Infrastructure changes require approval.",
      },
      {
        name: "The Technical Lead",
        title: "Tech Leadership Agent",
        desc: "Architecture ownership, tech strategy, code review oversight, team mentorship, sprint planning, CTO proxy",
        tools: ["Architecture Review", "Code Review", "Sprint Planning", "Tech Strategy", "Team Mentorship", "Risk Assessment"],
        confidence: "Code reviews autonomous. Architecture decisions require senior review.",
      },
      {
        name: "The UI/UX Designer",
        title: "Design Agent",
        desc: "Design ownership, wireframes, prototypes, user research, design systems, accessibility compliance",
        tools: ["Wireframing", "Prototyping", "User Research", "Design Systems", "Accessibility Audit", "Component Library"],
        confidence: "Design drafting autonomous. Final designs require stakeholder approval.",
      },
    ],
    process: [
      { step: "01", title: "Technical Assessment", desc: "We assess your tech stack, codebase, development workflows and team dynamics. Define sprint capacity and integration plan." },
      { step: "02", title: "Developer Matching", desc: "We match you with a developer whose skills align with your stack and domain. Meet your developer before commitment." },
      { step: "03", title: "Onboarding Sprint", desc: "First sprint: codebase familiarization, environment setup, first contributions. Developer joins all team ceremonies." },
      { step: "04", title: "Full Velocity", desc: "Developer operates at full capacity with AI augmentation. Regular performance reviews and velocity tracking." },
    ],
    deliverables: [
      "Dedicated developer (full-time or part-time)",
      "Sprint participation & daily standups",
      "Production-quality code with tests",
      "CI/CD pipeline setup & maintenance",
      "Technical documentation",
      "Monthly velocity & quality reports",
      "Cloud infrastructure management",
    ],
    faq: [
      { q: "What tech stacks do your developers cover?", a: "React/Next.js, Python/Django, Node.js, Flutter, Swift, Kotlin, PostgreSQL, MongoDB, AWS, GCP, Azure and more." },
      { q: "Can I interview the developer first?", a: "Absolutely. You meet and approve your developer before any commitment. If the fit isn't right, we match a different developer." },
      { q: "What's the difference between $500 and $1,800/mo?", a: "Entry ($500): part-time, ~20hrs/week. Growth ($1,000): dedicated, ~40hrs/week. Enterprise ($1,800): senior + junior pair, full coverage." },
      { q: "Do you handle DevOps as well?", a: "Yes — CI/CD, cloud infrastructure, monitoring, security patching and incident response are all included." },
    ],
  },
  {
    slug: "data-science",
    num: "07",
    icon: "📊",
    name: "Data Science",
    tagline: "Turn your data into decisions with AI-powered intelligence",
    price: "from $250/mo",
    priceNote: "Replaces $44,000+/mo in-house cost",
    roles: "Data Science · ML · Data Engineering · BI · Analytics",
    heroDesc: "Six specialized AI agents powering enterprise-grade data science — from predictive models and ETL pipelines to MLOps, business intelligence and board-ready analytical reports. A complete data team at a fraction of the cost.",
    color: "from-emerald-400/20 to-emerald-400/5",
    accentVar: "--color-teal",
    accent: "text-emerald-400",
    border: "border-emerald-400/20",
    saves: "$44,000+/mo",
    features: [
      "Predictive analytics & forecasting",
      "Custom ML model development",
      "Data cleaning & ETL pipelines",
      "Power BI / Tableau dashboards",
      "Generative AI & LLM integration",
    ],
    detailedFeatures: [
      { title: "KPI Dashboards", desc: "Real-time dashboards pulling data from finance, sales, marketing and operations. Customizable views for executives, managers and teams." },
      { title: "Predictive Analytics", desc: "Cash flow forecasting, revenue projections, churn prediction, demand planning and risk scoring using machine learning models." },
      { title: "Business Intelligence", desc: "Cross-functional analytics connecting financial performance, sales pipeline, marketing ROI and operational efficiency into unified executive views." },
      { title: "ML Model Development", desc: "Custom machine learning models for your specific business challenges — from customer segmentation to price optimization to anomaly detection." },
      { title: "Data Engineering", desc: "ETL pipeline design, data warehouse setup, data quality monitoring and automated data cleaning for reliable analytics foundations." },
      { title: "Strategy & Insights", desc: "Competitor benchmarking, market research, scenario modelling, risk assessment and growth strategy recommendations backed by data." },
    ],
    agents: [
      {
        name: "The Data Scientist",
        title: "ML & Predictive Agent",
        desc: "ML model development, feature engineering, model training/tuning, statistical analysis, predictive analytics",
        tools: ["Model Training", "Feature Engineering", "Statistical Analysis", "Prediction APIs", "Model Evaluation", "Experiment Tracking"],
        confidence: "Model development autonomous. Production model deployments require Tier 2 review.",
      },
      {
        name: "The Data Engineer",
        title: "Data Pipeline Agent",
        desc: "ETL/ELT pipelines, data warehouse design, source integrations, data quality validation, pipeline monitoring",
        tools: ["Pipeline Building", "Data Warehouse", "Source Integration", "Quality Validation", "Pipeline Monitoring", "Schema Management"],
        confidence: "Pipeline maintenance autonomous. Schema changes and new integrations require review.",
      },
      {
        name: "The ML Engineer",
        title: "MLOps Agent",
        desc: "Model deployment, MLOps, model monitoring, drift detection, automated retraining, API integration",
        tools: ["Model Deployment", "Drift Detection", "Auto-Retraining", "API Integration", "Performance Monitoring", "Version Control"],
        confidence: "Monitoring and alerting autonomous. Model retraining triggers require approval.",
      },
      {
        name: "The Business Analyst",
        title: "Business Analysis Agent",
        desc: "Requirements gathering, stakeholder reports, EDA, trend analysis, insight reports, data storytelling",
        tools: ["Requirements Docs", "EDA Reports", "Trend Analysis", "Stakeholder Briefs", "Insight Reports", "Data Storytelling"],
        confidence: "Analysis and reporting autonomous. Strategic recommendations flagged for review.",
      },
      {
        name: "The BI Developer",
        title: "BI Development Agent",
        desc: "Dashboard design, KPI tracking, data visualization, executive reporting, real-time analytics",
        tools: ["Dashboard Design", "KPI Configuration", "Data Visualization", "Executive Reports", "Real-time Feeds", "Alert Rules"],
        confidence: "Dashboard updates autonomous. New KPI definitions require stakeholder approval.",
      },
      {
        name: "The Data Analyst",
        title: "Data Analysis Agent",
        desc: "Ad-hoc analysis, SQL queries, statistical testing, funnel analysis, cohort analysis, reporting automation",
        tools: ["SQL Queries", "Statistical Tests", "Funnel Analysis", "Cohort Analysis", "Report Automation", "Data Export"],
        confidence: "Ad-hoc analysis fully autonomous. Published reports require Tier 1 review.",
      },
    ],
    process: [
      { step: "01", title: "Data Audit", desc: "We map all your data sources, assess quality, identify gaps and define the analytics roadmap." },
      { step: "02", title: "Infrastructure Setup", desc: "Data warehouse configuration, ETL pipelines, BI tool setup (Power BI/Tableau/SolyntaFlow) and initial dashboard design." },
      { step: "03", title: "Intelligence Layer", desc: "KPI dashboards deployed, forecasting models trained, automated reporting scheduled and executive views configured." },
      { step: "04", title: "Strategic Advisory", desc: "Monthly strategy sessions, competitor intelligence briefings, scenario planning and data-driven growth recommendations." },
    ],
    deliverables: [
      "Real-time KPI dashboards",
      "Monthly executive intelligence pack",
      "Cash flow & revenue forecasts",
      "Competitor intelligence reports",
      "Custom ML models (as needed)",
      "Data quality monitoring",
      "Quarterly strategy review",
    ],
    faq: [
      { q: "What BI tools do you use?", a: "Power BI, Tableau, Looker, Metabase and our built-in SolyntaFlow dashboards. We recommend based on your needs and budget." },
      { q: "Can you build custom ML models?", a: "Yes — from customer churn prediction to dynamic pricing to demand forecasting. Growth and Enterprise tiers include custom model development." },
      { q: "Do we need a data warehouse?", a: "For basic dashboards, no. For advanced analytics, we set up a lightweight warehouse (BigQuery, Snowflake or PostgreSQL) as part of onboarding." },
      { q: "How do you ensure data accuracy?", a: "Automated data quality checks, reconciliation rules, anomaly detection and human validation of all critical metrics." },
    ],
  },
  {
    slug: "enterprise-intelligence",
    num: "08",
    icon: "🧠",
    name: "Enterprise Intelligence",
    tagline: "Strategic oversight, compliance and AI-powered business intelligence",
    price: "from $500/mo",
    priceNote: "Replaces $25,000+/mo in-house cost",
    roles: "Strategy · Analytics · Compliance · AI Governance",
    heroDesc: "Four specialized agents providing the strategic intelligence layer every business needs — cross-functional KPI dashboards, competitor benchmarking, AI governance with confidence-based audit trails, and automated knowledge management.",
    color: "from-rose-400/20 to-rose-400/5",
    accentVar: "--color-coral",
    accent: "text-rose-400",
    border: "border-rose-400/20",
    saves: "$25,000+/mo",
    features: [
      "Cross-business KPI dashboards & forecasting",
      "Competitor benchmarking & market intelligence",
      "AI confidence scoring & audit trails",
      "Automated SOP extraction & knowledge bases",
      "Board-ready executive intelligence packs",
    ],
    detailedFeatures: [
      { title: "Executive Dashboards", desc: "Real-time KPI dashboards pulling data from finance, sales, marketing and operations into unified executive views. Customizable for board, C-suite and department leads." },
      { title: "Strategic Advisory", desc: "Competitor benchmarking, market research, scenario modelling, risk assessment and growth strategy recommendations backed by cross-functional data analysis." },
      { title: "AI Governance & Compliance", desc: "Confidence-based review of all AI agent outputs. Full audit trail for every automated action. Escalation enforcement ensuring human oversight at critical decision points." },
      { title: "Knowledge Management", desc: "Automated client onboarding data ingestion, SOP extraction from existing documents, AI readiness assessment and living knowledge base construction." },
    ],
    agents: [
      {
        name: "The Insight Engine",
        title: "Analytics & BI Agent",
        desc: "Cross-business KPI dashboards, variance analysis, trend forecasting, board-ready executive reporting",
        tools: ["Financial KPIs", "Pipeline Reports", "Support Summaries", "Traffic Analytics", "Chart Generation", "Board Packs", "Runway Modelling"],
        confidence: "Dashboard updates fully autonomous. Strategic recommendations flagged for Tier 2 review.",
      },
      {
        name: "The Strategy Advisor",
        title: "Strategic Intelligence Agent",
        desc: "Competitor benchmarking, market research, scenario modelling, risk assessment, growth strategy",
        tools: ["Company Research", "Competitor Analysis", "Financial KPIs", "Variance Analysis", "Forecasting", "Runway Modelling", "Board Packs"],
        confidence: "Research and analysis autonomous. All strategy recommendations require senior review.",
      },
      {
        name: "The Audit Sentinel",
        title: "Compliance & Governance Agent",
        desc: "Confidence-based review of AI outputs, audit trail management, compliance monitoring, escalation enforcement",
        tools: ["Audit Trail", "Confidence Scoring", "Compliance Checks", "Escalation Rules", "Risk Flagging", "Review Queue"],
        confidence: "Audit logging fully autonomous. Compliance violations always escalated to human review.",
      },
      {
        name: "The Knowledge Architect",
        title: "Onboarding & Knowledge Agent",
        desc: "Client data ingestion, AI readiness assessment, SOP extraction, knowledge base building and maintenance",
        tools: ["Data Ingestion", "SOP Extraction", "KB Building", "AI Readiness Scan", "Document Processing", "Taxonomy Design"],
        confidence: "Data ingestion autonomous. Knowledge base structure and SOP definitions require client approval.",
      },
    ],
    process: [
      { step: "01", title: "Intelligence Audit", desc: "We map all data sources, assess current reporting, identify blind spots and define the intelligence roadmap." },
      { step: "02", title: "Dashboard Deploy", desc: "Executive dashboards configured, KPIs defined, forecasting models trained and automated reporting scheduled." },
      { step: "03", title: "Governance Setup", desc: "AI confidence scoring calibrated, audit trail configured, escalation rules defined and compliance monitoring activated." },
      { step: "04", title: "Strategic Advisory", desc: "Monthly strategy sessions, competitor intelligence briefings, scenario planning and data-driven growth recommendations." },
    ],
    deliverables: [
      "Real-time executive KPI dashboards",
      "Monthly competitor intelligence briefing",
      "AI governance & compliance reports",
      "Cash flow & revenue forecasts",
      "Living knowledge base & SOPs",
      "Quarterly strategic review",
    ],
    faq: [
      { q: "How is this different from Data Science?", a: "Data Science builds models and pipelines. Enterprise Intelligence provides the strategic layer — executive dashboards, competitor research, AI governance and knowledge management that sits above all other modules." },
      { q: "Do we need this if we have Finance Core?", a: "Finance Core handles accounting. Enterprise Intelligence provides cross-functional intelligence spanning all departments — connecting financial, sales, marketing and operational data into unified strategic views." },
      { q: "What's included in AI governance?", a: "Confidence scoring on all AI agent outputs, full audit trail, escalation enforcement, compliance monitoring and regular governance reports for your leadership team." },
      { q: "Can this module work standalone?", a: "Yes, but it delivers the most value when combined with other modules, as it aggregates intelligence across all active services." },
    ],
  },
  {
    slug: "inventory-management",
    num: "09",
    icon: "📦",
    name: "Inventory Management",
    tagline: "AI-powered stock control, forecasting and supply chain optimization",
    price: "from $250/mo",
    priceNote: "Replaces $18,000+/mo in-house cost",
    roles: "Stock Control · Procurement · Forecasting · Warehouse",
    heroDesc: "Four AI agents managing your entire supply chain — from stock control and procurement to demand forecasting and warehouse operations. Multi-warehouse, multi-site, e-commerce integrated.",
    color: "from-amber-400/20 to-amber-400/5",
    accentVar: "--color-gold",
    accent: "text-amber-400",
    border: "border-amber-400/20",
    saves: "$18,000+/mo",
    features: [
      "Unlimited SKU management",
      "Multi-warehouse & multi-site",
      "AI-powered demand forecasting",
      "BOM & MRP for manufacturing",
      "Shopify / WooCommerce sync",
    ],
    detailedFeatures: [
      { title: "SKU Management", desc: "Unlimited product catalog with variants, barcoding, batch/lot tracking, serial numbers and custom attributes. Full product lifecycle management." },
      { title: "Multi-Warehouse", desc: "Track inventory across multiple warehouses, retail locations and fulfilment centres. Inter-warehouse transfers, bin location tracking and cycle counting." },
      { title: "Demand Forecasting", desc: "AI-powered demand prediction using historical sales data, seasonality patterns, market trends and promotional calendars. Auto-generate reorder suggestions." },
      { title: "Bill of Materials & MRP", desc: "Multi-level BOM management, material requirements planning, work order generation, production scheduling and raw material procurement triggers." },
      { title: "E-Commerce Integration", desc: "Real-time sync with Shopify, WooCommerce, Amazon and other marketplaces. Automatic stock level updates, order pulling and fulfilment tracking." },
      { title: "Supply Chain Analytics", desc: "Lead time analysis, supplier performance scoring, carrying cost optimization, dead stock identification and turnover rate dashboards." },
    ],
    agents: [
      {
        name: "The Inventory Controller",
        title: "Stock Management Agent",
        desc: "Stock management, cycle counts, write-offs, multi-warehouse operations, stock level monitoring, reorder management",
        tools: ["Stock Tracking", "Cycle Counting", "Write-off Processing", "Multi-Warehouse Ops", "Stock Alerts", "Reorder Management"],
        confidence: "Stock alerts fully autonomous. Purchase orders and reorder triggers require operator approval.",
      },
      {
        name: "The Procurement Analyst",
        title: "Procurement Agent",
        desc: "PO creation/tracking, supplier management, GRN processing, 3-way matching, cost optimization",
        tools: ["PO Management", "Supplier Scoring", "GRN Processing", "3-Way Matching", "Cost Analysis", "Vendor Onboarding"],
        confidence: "PO tracking autonomous. New supplier onboarding and large POs require Tier 2 approval.",
      },
      {
        name: "The Demand Forecaster",
        title: "Forecasting Agent",
        desc: "AI-powered demand forecasting, seasonal analysis, safety stock optimization, reorder point tuning",
        tools: ["Demand Modelling", "Seasonal Analysis", "Safety Stock Calc", "Reorder Optimization", "Trend Detection", "Forecast Reports"],
        confidence: "Forecasting fully autonomous. Reorder parameter changes require operator review.",
      },
      {
        name: "The Warehouse Manager",
        title: "Warehouse Ops Agent",
        desc: "Warehouse operations, bin management, pick/pack/dispatch, barcode/RFID workflows, space optimization",
        tools: ["Bin Management", "Pick Lists", "Pack/Dispatch", "Barcode/RFID", "Space Optimization", "Receiving"],
        confidence: "Warehouse operations autonomous. Layout changes and new zone configurations require approval.",
      },
    ],
    process: [
      { step: "01", title: "Inventory Audit", desc: "Physical stock count, SKU rationalization, warehouse mapping and current system assessment." },
      { step: "02", title: "System Setup", desc: "Product catalog import, warehouse configuration, BOM setup, reorder rules and e-commerce integration." },
      { step: "03", title: "Forecasting Calibration", desc: "Historical data analysis, demand pattern identification, seasonality modelling and reorder point optimization." },
      { step: "04", title: "Managed Operations", desc: "Ongoing stock management, automated reorder alerts, demand forecasting updates and monthly supply chain reports." },
    ],
    deliverables: [
      "Complete product catalog management",
      "Multi-warehouse stock tracking",
      "AI demand forecasting reports",
      "Automated reorder alerts",
      "E-commerce platform sync",
      "Monthly inventory performance report",
      "Supply chain optimization recommendations",
    ],
    faq: [
      { q: "What e-commerce platforms do you integrate with?", a: "Shopify, WooCommerce, Magento, Amazon, eBay and custom platforms via API." },
      { q: "Can you handle manufacturing/BOM?", a: "Yes — multi-level BOMs, work orders, MRP runs and production scheduling are included in Growth and Enterprise tiers." },
      { q: "Do you support barcode/RFID scanning?", a: "Yes. SolyntaFlow supports barcode scanning via mobile app and integrates with RFID systems for warehouse management." },
      { q: "How accurate is the demand forecasting?", a: "Typically 85-92% accuracy after 3 months of calibration, depending on data quality and product category variability." },
    ],
  },
];

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return services.find((s) => s.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return services.map((s) => s.slug);
}
